### PR TITLE
Remove unnecessary interfaces of k8s pkg

### PR DESCRIPTION
**Pull request by drgarcia1986**
Golang is smart enough to infer the interfaces on business packages.

### CODE REVIEW

**Comment by yagonobre** [comment]
Maybe an entry in the changelog?

**Comment by drgarcia1986** [comment]
@yagonobre IDK, that diff doesn't change the behavior of the application, but I'm not against the changelog, @aguerra  what do you think about it?

**Comment by aguerra** [comment]
@drgarcia1986 I like the rule no change in behavior, no changelog

**Comment by drgarcia1986** [comment]
@aguerra about the gold rule `three letter variable names`, LGTM 👍 but, `k8s` is a pkg name on Teresa, is there another suggestion?

**Comment by drgarcia1986** [comment]
@aguerra what about `kc`? (ok, I know, is only 2 letters 😝  )

**Pull request merged**
